<a href="https://colab.research.google.com/github/RuthStowers/MAT422/blob/main/Homework_1_3_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 1.3 - Linear Regression


---



# 1.3.1 QR Decomposition
QR decomposition is a useful procedure to solve the linear least squares
problem. QR factorization takes the general form $A = QR$ where $Q$ is the product of the Gram-Schmidt process, and $R$ is an upper triangular matrix as follows.

In [1]:
import numpy as np

In [3]:
A = np.random.randint(10, size = (3, 3))
q, r = np.linalg.qr(A)
print('A: \n', A, '\n')
print('Q: \n', q, '\n')
print('R: \n', r, '\n')

A: 
 [[2 2 8]
 [8 0 8]
 [7 2 9]] 

Q: 
 [[-0.18490007  0.73994007 -0.64676167]
 [-0.73960026 -0.53813824 -0.40422604]
 [-0.64715023  0.40360368  0.64676167]] 

R: 
 [[-10.81665383  -1.66410059 -13.22035468]
 [  0.           2.2870875    5.24684779]
 [  0.           0.          -2.58704667]] 



In [4]:
p = (np.matmul(q, r))
print(p, '\n')
print(A)


[[ 2.00000000e+00  2.00000000e+00  8.00000000e+00]
 [ 8.00000000e+00 -7.42777761e-16  8.00000000e+00]
 [ 7.00000000e+00  2.00000000e+00  9.00000000e+00]] 

[[2 2 8]
 [8 0 8]
 [7 2 9]]


As you can see from the above code, $Q$ dotted with $R$ gives us back $A$.



# 1.3.2 Least-squares Problems
We are trying to solve for the system $Ax = b$ where $A$ is an $n$ x $m$ matrix and $n > m$. If $n = m$, then we could just find the matrix inverse.
Instead, we find an $Ax$ such that we minimize $\|Ax-b\|$.

In [5]:
b = np.random.randint(10, size = (3, 1))
x = np.matmul(np.matmul(np.linalg.inv(r),np.transpose(q)), b)
Ax = np.matmul(A, x)
print('solution vector: \n', x, '\n')
print('b: \n', b, '\n')
print('Ax: \n', Ax, '\n')


solution vector: 
 [[-0.75]
 [-0.75]
 [ 0.75]] 

b: 
 [[3]
 [0]
 [0]] 

Ax: 
 [[3.]
 [0.]
 [0.]] 



As you can see from the above code, we generate a random $b$ vector and use the random $A, Q, R$ values from the previous QR decomposition example. $Ax$ should give a close approximation to $b$.

# 1.3.3 Linear Regression
Linear regression seeks to find an affine function to fit a data set as closely as possible. This is a minimization problem and when looked at in matrix form, is the exact same as the least-squares problem. Linear Regression is often used as a method of statistical analysis.